In [162]:
import numpy as np
from scipy.sparse import diags


A:

In [163]:
def A(n):
    sp = diags([[2]*n,-1,-1],[0,1,-1])
    sp = sp.toarray()

    sp = (n+1)**2 * sp
    print(sp)
    return sp
A = A(10)


[[ 242. -121.    0.    0.    0.    0.    0.    0.    0.    0.]
 [-121.  242. -121.    0.    0.    0.    0.    0.    0.    0.]
 [   0. -121.  242. -121.    0.    0.    0.    0.    0.    0.]
 [   0.    0. -121.  242. -121.    0.    0.    0.    0.    0.]
 [   0.    0.    0. -121.  242. -121.    0.    0.    0.    0.]
 [   0.    0.    0.    0. -121.  242. -121.    0.    0.    0.]
 [   0.    0.    0.    0.    0. -121.  242. -121.    0.    0.]
 [   0.    0.    0.    0.    0.    0. -121.  242. -121.    0.]
 [   0.    0.    0.    0.    0.    0.    0. -121.  242. -121.]
 [   0.    0.    0.    0.    0.    0.    0.    0. -121.  242.]]


In [164]:
def eigenvalues(A):
    n = A.shape[0]
    eigs = []
    for k in range(1, n+1):
        eigs.append(4*(n+1)**2*np.sin(k*np.pi/(2*(n+1)))**2)
    print(np.sort(eigs))
    return np.sort(eigs)


In [165]:
def QR(A):
    Q = np.eye(A.shape[0])
    R = A
    for k in range(A.shape[1]):
        x = R[k:, k]
        e = np.zeros(len(x))
        e[0] = 1
        v = np.sign(x[0]) * np.linalg.norm(x) * e + x
        v = v / np.linalg.norm(v)
        Qk = np.eye(A.shape[0])
        Qk[k:, k:] -= 2 * np.outer(v, v)
        Q = Q @ Qk
        R = Qk @ R
        
    return Q, R

In [166]:
def eigenvalue_calculation(A, tolerance):
    A_tmp = A
    eigs = []
    while(1 < A_tmp.shape[0]):

        while(tolerance < abs(A_tmp[-2,-1])):
            mu = A_tmp[-1,-1]+tolerance
            A_tmp = A_tmp-(mu*np.eye(A_tmp.shape[0]))
            Q,R = QR(A_tmp)
            A_tmp = R@Q + (mu*np.eye(A_tmp.shape[0]))

        eigs.append(A_tmp[-1,-1])
        A_tmp = A_tmp[:-1,:-1]

        if (A_tmp.shape[0] == 1):
            eigs.append(A_tmp[0][0])
    print(np.sort(eigs))
    return np.sort(eigs)


In [167]:
tolerance = 1e-8
eigs_by_iter = eigenvalue_calculation(A, tolerance)
eigs_by_equ = eigenvalues(A)

print('Yay, we got the same eigenvalues :)' if (np.max(np.abs(eigs_by_iter - eigs_by_equ)) < tolerance) else 'Try again :(')

[  9.80270039  38.41664505  83.52370239 141.46956685 207.55980914
 276.44019086 342.53043315 400.47629761 445.58335495 474.19729961]
[  9.80270039  38.41664505  83.52370239 141.46956685 207.55980914
 276.44019086 342.53043315 400.47629761 445.58335495 474.19729961]
Yay, we got the same eigenvalues :)
